### ISSUE TITLE
Review of the docs

### ISSUE THREAD

**Issue by guipublic** [noir-lang/book#13]
Here are some remarks regarding the documentation:

> Installing Noir from the Compiled Binary  

We should update the binaries

> Note: At the time of pre-alpha, Nargo supports only one backend which is Aztec-Barretenberg.  

I guess we are now in pre-beta instead of pre-alpha, and we do support another backend. However only the Aztec one is compatible with the ethereum contract.

> TornadoCash:

Section is empty, may be we want to rename it as well?

> This should generally be the default type reached for to solve problems as using a smaller integer type like u64 incurs extra range constraints and so is less efficient rather than more.

it seems convoluted to me. But being not a native english speaker, I may be totally wrong.

>Note: The Aztec backend only supports even sized integer types currently, so while using the Aztec backend, only even sized integer types such as u32, u48 will produce proofs.

This should not be true anymore, odd-sized integers should be fine.

> f a constant type that is being used in your program in changed, 

typo; 'in' should be  'IS'

> Note: This behaviour (n.b. pub in main arguments) and type will change in future releases, to catch a linearity bug in user code.

Why this behavior will change?

>An array is a data structure which allows you to group together data types

 to group together data of the same type

> Note that currently Noir only supports arrays with integer or field elements.

we do not support array of struct?

> Example: An array of Witness types cannot be grouped together with an array of Integer type

an array of Field (instead of witness)

>For loops are expressions, so each iteration of the loop produces a value which is collected into an array.
The following code **produces an array** of 10 values, each element contains the same values from 0 to 9.
let my_arr = for i in 0..10 {
    i
};

 I don't think this is working anymore

> If Expressions
    Currently, these are not supported in the language.

yes they are!

```
<	constrains one value to be less than the other			Upper bound must have a known bit size
<=	constrains one value to be less than or equal to the other	Upper bound must have a known bit size
>	constrains one value to be more than the other			Upper bound must have a known bit size
>=	constrains one value to be more than or equal to the other	Upper bound must have a known bit size
==	constrains one value to be equal to the other			Both types must not be constants
!=	constrains one value to not be equal to the other		Both types must not be constants
```

It does not constrains, it returns a bool value.
Types can be constant, 
for the known bit size, I am not sure, but it is probably the case (that it must be known)

> they compare two values. This differs from the operations such as + where the operands are used in computation.

Not sure it is correct, because you can use comparisons in computations.

> you can use the bitwise operators | and & which operate indentically for booleans, just without the short-circuiting

an example would be welcome

>Features Coming Soon
If Statement / Ternary Expression

IF statement are done.

>Currently only primitives types are available. This does not hinder expressiveness, however for large circuits, readability will be harmed without structs.

Struct are done

> Isize
Signed integers such as i32 and i64 allow one to express more circuits.

signed integers are partially supported, they should really be finalised.

**Comment by vezenovm** [comment]
> I guess we are now in pre-beta instead of pre-alpha, and we do support another backend. However only the Aztec one is compatible with the ethereum contract.

Do you mean the arkworks backend's like Marlin? I don't know if we can say that we fully support them yet as they only support arithmetic gates. We still need to add some logic that converts our custom gates to arithmetic gates. We can build Noir with Marlin for example but simple examples still fail. 

> Section is empty, may be we want to rename it as well?

Looks like the master branch of the book has details here and has been renamed to Merkle Membership. Most likely just need to update the github pages

> it seems convoluted to me. But being not a native english speaker, I may be totally wrong.

I can try and re-word this in a PR to update the docs

> This should not be true anymore, odd-sized integers should be fine.

I still got this error on Noir `master` branch

<img width="1045" alt="Screen Shot 2022-09-28 at 10 15 55 PM" src="https://user-images.githubusercontent.com/43554004/192923393-e5b98db0-b7a5-4b29-9279-4fdd7fce783d.png">

**Comment by vezenovm** [comment]
> > Note: This behaviour (n.b. pub in main arguments) and type will change in future releases, to catch a linearity bug in user code.
> 
> Why this behavior will change?

Curious about this as well. Do you have any insight into this note @kevaundray ?

**Comment by guipublic** [comment]
>  >  ...odd-sized integers should be fine.

> I still got this error on Noir master branch

Good point! I removed this todo in PR #354

**Comment by Globallager** [comment]
Most comments seem to have been addressed in previous PRs. https://github.com/noir-lang/book/pull/42 should address  the remaining ones below: 

>> This should generally be the default type reached for to solve problems as using a smaller integer type like u64 incurs extra range constraints and so is less efficient rather than more.
>
> it seems convoluted to me. But being not a native english speaker, I may be totally wrong.

Reworded: https://github.com/noir-lang/book/pull/42/files#diff-f83b6591dd0f46043bcc78d734fc1ca6174383d5e406b1662e554c116e203166R57

>> Note: This behaviour (n.b. pub in main arguments) and type will change in future releases, to catch a linearity bug in user code.
>
> Why this behavior will change?

Deleted: https://github.com/noir-lang/book/pull/42/files#diff-f83b6591dd0f46043bcc78d734fc1ca6174383d5e406b1662e554c116e203166L127

>> An array is a data structure which allows you to group together data types
>
> to group together data of the same type

Reworded: https://github.com/noir-lang/book/pull/42/files#diff-f83b6591dd0f46043bcc78d734fc1ca6174383d5e406b1662e554c116e203166R96

>> Note that currently Noir only supports arrays with integer or field elements.
>
> we do not support array of struct?

I don't think we do yet. We can modify this when we've added support.
